name: "release"
on:
  release:
    types:
      - published
      - edited

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainers-ci
          push: never
          runCmd: |
            npm ci
            npm run build

      - name: Build and Tag
        uses: JasonEtco/build-and-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: report result
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
